### ISSUE TITLE
Crashing issues

### ISSUE THREAD

**Issue by Kliurka** [sk1project/sk1-wx#10]
Crashing issues on Ubuntu 15.10  4.2.0-18-generic x86_64

> 

_bar@bar-desktop:~$ sk1
Traceback (most recent call last):
  File "/usr/bin/sk1", line 15, in <module>
    sk1_run()
  File "/usr/lib/sk1-wx-2.0rc1/sk1/__init__.py", line 57, in sk1_run
    app.run()
  File "/usr/lib/sk1-wx-2.0rc1/wal/basic.py", line 66, in run
    self.mw.build()
  File "/usr/lib/sk1-wx-2.0rc1/sk1/parts/mw.py", line 47, in build
    self.menubar = AppMenuBar(self.app, self)
  File "/usr/lib/sk1-wx-2.0rc1/sk1/parts/menubar.py", line 35, in __init__
    (_("Open &Recent"), (HistoryMenu(self.app, self.mw),)),
  File "/usr/lib/sk1-wx-2.0rc1/sk1/parts/menubar.py", line 180, in __init__
    self.empty_item.Enable(False)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 12507, in Enable
    return _core_.MenuItem_Enable(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "m_menuItem" failed at ../src/gtk/menu.cpp(751) in Enable(): invalid menu item_

>

**Comment by sk1project** [comment]
This is wxgtk3.0 issue. The problem has been fixed in trunk.
