### ISSUE TITLE
Errors in the Trafo of objects of zero width or height

### ISSUE THREAD

**Issue by maxim-s-barabash** [sk1project/sk1-wx#164]
Trafo a vertical or horisontal line leads to an errors
```
file "sk1-wx/src/sk1/pwidgets/surfaces.py", line 210, in mouse_move
    self.painter.controller.mouse_move(event)
  File "sk1-wx/src/sk1/document/controllers/trafo_ctrl.py", line 224, in mouse_move
    self.trafo = self._calc_trafo(event)
  File "sk1-wx/src/sk1/document/controllers/trafo_ctrl.py", line 467, in _calc_trafo
    m22 = (h + dy) / h
ZeroDivisionError: float division by zero
```

```
 File "sk1-wx/src/sk1/pwidgets/surfaces.py", line 210, in mouse_move
    self.painter.controller.mouse_move(event)
  File "sk1-wx/src/sk1/document/controllers/trafo_ctrl.py", line 224, in mouse_move
    self.trafo = self._calc_trafo(event)
  File "/k1-wx/src/sk1/document/controllers/trafo_ctrl.py", line 928, in _calc_trafo
    m12 = change_x / h
ZeroDivisionError: float division by zero

```

```
  File "sk1-wx/src/sk1/pwidgets/surfaces.py", line 210, in mouse_move
    self.painter.controller.mouse_move(event)
  File "sk1-wx/src/sk1/document/controllers/trafo_ctrl.py", line 224, in mouse_move
    self.trafo = self._calc_trafo(event)
  File "sk1-wx/src/sk1/document/controllers/trafo_ctrl.py", line 616, in _calc_trafo
    m11 = (w + dx) / w
ZeroDivisionError: float division by zero
```

```
Traceback (most recent call last):
  File "sk1-wx/src/sk1/pwidgets/surfaces.py", line 210, in mouse_move
    self.painter.controller.mouse_move(event)
  File "sk1-wx/src/sk1/document/controllers/trafo_ctrl.py", line 224, in mouse_move
    self.trafo = self._calc_trafo(event)
  File "sk1-wx/src/sk1/document/controllers/trafo_ctrl.py", line 936, in _calc_trafo
    m21 = change_y / w
ZeroDivisionError: float division by zero

```

**Comment by maxim-s-barabash** [comment]
Fixed https://github.com/sk1project/sk1-wx/commit/77cbb9c19fa001d46bfc05a7d223a1fc9e28c5c8
