### ISSUE TITLE
svg,  not correctly processed viewbox

### ISSUE THREAD

**Issue by maxim-s-barabash** [sk1project/sk1-wx#169]
```
Traceback (most recent call last):
  File "/sk1-wx/src/wal/modaldlgs.py", line 251, in on_load
    self.result = self.callback(*self.args)
  File "/sk1-wx/src/uc2/formats/svg/__init__.py", line 36, in svg_loader
    svg_doc.translate_to_sk2(sk2_doc)
  File "/sk1-wx/src/uc2/formats/svg/svg_presenter.py", line 67, in translate_to_sk2
    translator.translate(self, sk2_doc)
  File "/sk1-wx/src/uc2/formats/svg/svg_translators.py", line 108, in translate
    self.translate_page()
  File "sk1-wx/src/uc2/formats/svg/svg_translators.py", line 554, in translate_page
    dy = -vbox[1]
TypeError: bad operand type for unary -: 'NoneType'

```

Example file:

```svg
<svg width = "600px" height="600px" viewBox = "-200, -200, 600, 600">
  <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
</svg> 
```

https://github.com/sk1project/sk1-wx/blob/8447d7559a3d939e9b59c613391d58430970e5b7/src/uc2/formats/svg/svg_translators.py#L165

```diff
-        return [self.recalc_size(item) for item in items]
+        return [self.recalc_size(item) for item in items if item]
```

but still need to check the correctness viewbox

**Comment by sk1project** [comment]
@maxim-s-barabash fixed
