### ISSUE TITLE
ERROR Document saved float division by zero

### ISSUE THREAD

**Issue by maxim-s-barabash** [sk1project/sk1-wx#182]
Create a new document.
Create a vertical line (height 0.0).
Save the document.

```
ERROR    | 08:01:53 PM | uc2.formats.generic_filters --> Error saving file content float division by zero
ERROR    | 08:01:53 PM | uc2.formats.generic --> Error while saving /home/max/Project/sk1-test/xar/test/12/Untitled 1.sk2 %s
ERROR    | 08:01:53 PM | wal.modaldlgs --> Error in progress dialog running: float division by zero
Traceback (most recent call last):
  File "/home/max/Project/sk1-wx/src/wal/modaldlgs.py", line 251, in on_load
    self.result = self.callback(*self.args)
  File "/home/max/Project/sk1-wx/src/uc2/formats/sk2/__init__.py", line 36, in sk2_saver
    sk2_doc.save(filename, fileptr)
  File "/home/max/Project/sk1-wx/src/uc2/formats/generic.py", line 171, in save
    self.saver.save(self, filename, fileptr)
  File "/home/max/Project/sk1-wx/src/uc2/formats/generic_filters.py", line 209, in save
    self.do_save()
  File "/home/max/Project/sk1-wx/src/uc2/formats/sk2/sk2_filters.py", line 103, in do_save
    preview = self.generate_preview()
  File "/home/max/Project/sk1-wx/src/uc2/formats/sk2/sk2_filters.py", line 160, in generate_preview
    coef = min(wp / w, hp / h) * 0.99
ZeroDivisionError: float division by zero
 INFO     | 08:01:53 PM | sk1.application --> Document saved
```

**Comment by sk1project** [comment]
fixed
