### ISSUE TITLE
error svg to wmf on windows 10

### ISSUE THREAD

**Issue by lhpitn** [sk1project/sk1-wx#192]
hi, i'm trying to insert an svg into powerpoint without converting it to png, so i need wmf (as of microsoft disabled its eps support ;( ) So i found your tool but ive got this error:

````
C:\Users\user\Downloads>uniconvertor avatar-1300582.svg avatar-1300582.wmf
Traceback (most recent call last):
  File "C:\Program Files (x86)\sK1 Project\UniConvertor-1.1.5\lib\site-packages\sk1libs\filters\import\svgloader.py", line 1305, in Load
    xml_reader.parse(input_source)
  File "C:\Program Files (x86)\sK1 Project\UniConvertor-1.1.5\lib\xml\sax\expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\Program Files (x86)\sK1 Project\UniConvertor-1.1.5\lib\xml\sax\xmlreader.py", line 125, in parse
    self.close()
  File "C:\Program Files (x86)\sK1 Project\UniConvertor-1.1.5\lib\xml\sax\expatreader.py", line 218, in close
    self._cont_handler.endDocument()
  File "C:\Program Files (x86)\sK1 Project\UniConvertor-1.1.5\lib\site-packages\sk1libs\filters\import\svgloader.py", line 559, in endDocument
    self.parseElements(element)
  File "C:\Program Files (x86)\sK1 Project\UniConvertor-1.1.5\lib\site-packages\sk1libs\filters\import\svgloader.py", line 579, in parseElements
    getattr(self, method)(attrs)
  File "C:\Program Files (x86)\sK1 Project\UniConvertor-1.1.5\lib\site-packages\sk1libs\filters\import\svgloader.py", line 475, in stop
    style=attrs['style']
  File "C:\Program Files (x86)\sK1 Project\UniConvertor-1.1.5\lib\xml\sax\xmlreader.py", line 316, in __getitem__
    return self._attrs[name]
KeyError: 'style'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\sK1 Project\UniConvertor-1.1.5\lib\site-packages\uniconvertor\__init__.py", line 95, in uniconv_run
    doc = load.load_drawing(input_file)
  File "C:\Program Files (x86)\sK1 Project\UniConvertor-1.1.5\lib\site-packages\uniconvertor\app\io\load.py", line 377, in load_drawing
    return load_drawing_from_file(file, filename)
  File "C:\Program Files (x86)\sK1 Project\UniConvertor-1.1.5\lib\site-packages\uniconvertor\app\io\load.py", line 354, in load_drawing_from_file
    raise SketchLoadError(_("Parsing error: ")+ str(value))
app.events.skexceptions.SketchLoadError: Parsing error: 'style'

C:\Users\user\Downloads>


````
thanks in advance, ill attach the source file

[avatar-1300582.svg.zip](https://github.com/sk1project/sk1-wx/files/3176365/avatar-1300582.svg.zip)

edit: attachment inline on wrong position fixed

**Comment by sk1project** [comment]
@lhpitn I checked you file and in common view it cannot be exported into WMF because it contains elements with alpha channel. Also in nearest feature we will publish newer UniConvertor version which will be better for such operations. Version 1.1.5 is outdated and bugged.
