### ISSUE TITLE
does not print either to the file or to the printer

### ISSUE THREAD

**Issue by maxim-s-barabash** [sk1project/sk1-wx#207]
sK1 the rc5 version
```ERROR    | 12:21:34 AM | wal.modaldlgs --> Error in progress dialog running: __init__() got an unexpected keyword argument 'invariant'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 418, in format
    IOf = IO.format(self)
  File "/usr/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 866, in format
    fcontent = format(self.content, document, toplevel=1)   # yes this is at top level
  File "/usr/lib/python2.7/dist-packages/reportlab/pdfbase/pdfdoc.py", line 80, in format
    f = element.format(document)
  File "Project2/uniconvertor/src/uc2/formats/pdf/pdfgen.py", line 43, in format
    dateFormatter=self._dateFormatter),
TypeError: __init__() got an unexpected keyword argument 'invariant'

```
Changes on reportlab

https://bitbucket.org/rptlab/reportlab/commits/d39c63b164bc875345e0dc8968755f258c01c7bf#Lsrc/reportlab/pdfbase/pdfdoc.pyF151

**Comment by sk1project** [comment]
@maxim-s-barabash plz check fix in master

**Comment by maxim-s-barabash** [comment]
https://github.com/sk1project/uniconvertor/commit/2e17e7d4bd9ddeddc2b9c1a3730a61c5fba66af6
pdf file generated. but in the meta-information there is no CreationDate, as previously planned
