### ISSUE TITLE
skp does not convert to gpl

### ISSUE THREAD

**Issue by maxim-s-barabash** [sk1project/sk1-wx#231]
uc2 palette.skp palette.skp.gpl
```
Traceback (most recent call last):
  File "~/Project2/uniconvertor/src/uc2/cmds/translate.py", line 102, in convert
    **options)
  File "~/Project2/uniconvertor/src/uc2/formats/gpl/__init__.py", line 61, in gpl_saver
    gpl_doc.convert_from_skp(doc)
  File "~/Project2/uniconvertor/src/uc2/formats/gpl/gpl_presenter.py", line 60, in convert_from_skp
    self.model.name = skp_model.name
AttributeError: 'Document' object has no attribute 'name'
```

**Comment by TiagoX84** [comment]
Hello SK1 does not convert vector to bitmap. This function is not enabled, it only has a way to convert and is not converting.

**Comment by sk1project** [comment]
@TiagoX84 which translation are you expecting? You can save vector graphics as a bitmap using Iconizer plugin.

**Comment by sk1project** [comment]
the issue has been fixed
