### ISSUE TITLE
startup error on debian testing (buster)

### ISSUE THREAD

**Issue by antoniusz** [sk1project/sk1-wx#71]
Hi,
I've got this error on startup (self-built deb package, from git master):

Traceback (most recent call last):
  File "/usr/bin/sk1", line 22, in <module>
    sk1_run()
  File "/usr/lib/sk1-wx-2.0rc3/sk1/__init__.py", line 53, in sk1_run
    from sk1.application import SK1Application
  File "/usr/lib/sk1-wx-2.0rc3/sk1/application.py", line 25, in <module>
    import wal
  File "/usr/lib/sk1-wx-2.0rc3/wal/__init__.py", line 19, in <module>
    from basic import *
  File "/usr/lib/sk1-wx-2.0rc3/wal/basic.py", line 23, in <module>
    import const
  File "/usr/lib/sk1-wx-2.0rc3/wal/const.py", line 151, in <module>
    IS_UNITY_16 = is_unity_16_04()
  File "/usr/lib/sk1-wx-2.0rc3/wal/const.py", line 137, in is_unity_16_04
    ver = int(platform.dist()[1].split('.')[0])
ValueError: invalid literal for int() with base 10: 'buster/sid'

**Comment by antoniusz** [comment]
related to #65

**Comment by sk1project** [comment]
The problem has been fixed.
