### ISSUE TITLE
outside Text on circle failure

### ISSUE THREAD

**Issue by maxim-s-barabash** [sk1project/sk1-wx#73]
[textoncircle.zip](https://github.com/sk1project/sk1-wx/files/1843885/textoncircle.zip)

```
Traceback (most recent call last):
  File "git/sk1-wx/src/wal/widgets.py", line 178, in on_click
    self.callback()
  File "git/sk1-wx/src/sk1/share/pd_plugins/text_on_circle/__init__.py", line 226, in action
    not self.other_side.get_value())
  File "git/sk1-wx/src/sk1/document/api.py", line 2081, in place_text_on_circle
    group.set_text_on_path(circle, text_obj, childs_data)
  File "git/sk1-wx/src/uc2/formats/sk2/sk2_model.py", line 508, in set_text_on_path
    libgeom.set_text_on_path(path_obj, text_obj, data)
  File "git/sk1-wx/src/uc2/libgeom/text_on_path.py", line 56, in set_text_on_path
    fpath = flat_path(path)
  File "git/sk1-wx/src/uc2/libgeom/flattering.py", line 72, in flat_path
    ret_points += flat_segment(start, point, tlr)[1:]
  File "git/sk1-wx/src/uc2/libgeom/flattering.py", line 55, in flat_segment
    p1, p2 = split_segment(start_point, end_point)
  File "git/sk1-wx/src/uc2/libgeom/flattering.py", line 28, in split_segment
    p1, p2, p3, flag = end_point
ValueError: need more than 3 values to unpack
```

**Comment by sk1project** [comment]
fixed
