### ISSUE TITLE
Create text UnicodeEncodeError

### ISSUE THREAD

**Issue by maxim-s-barabash** [sk1project/sk1-wx#97]
I paste the text "cześć" and get an error

```bash
Traceback (most recent call last):
  File "/home/max/git/sk1-wx/src/sk1/pwidgets/actions.py", line 132, in do_call
    self.callback()
  File "/home/max/git/sk1-wx/src/sk1/app_proxy.py", line 298, in paste
    doc.canvas.controller.replace_selected(wal.get_text_from_clipboar())
  File "/home/max/git/sk1-wx/src/sk1/document/controllers/text_ctrl.py", line 203, in replace_selected
    self.insert_text(text)
  File "/home/max/git/sk1-wx/src/sk1/document/controllers/text_ctrl.py", line 540, in insert_text
    self.update_target()
  File "/home/max/git/sk1-wx/src/sk1/document/controllers/text_ctrl.py", line 111, in update_target
    deepcopy(self.markup))
  File "/home/max/git/sk1-wx/src/sk1/document/api.py", line 1979, in change_text
    self._set_text_data(obj, text_after, trafos_after, markup_after)
  File "/home/max/git/sk1-wx/src/sk1/document/api.py", line 379, in _set_text_data
    text_obj.set_text(text)
  File "/home/max/git/sk1-wx/src/uc2/formats/sk2/sk2_model.py", line 923, in set_text
    self.text = b64encode(text)
  File "/usr/lib/python2.7/base64.py", line 54, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-4: ordinal not in range(128)
```

CLUTTER_IM_MODULE=xim
GTK_MODULES=gail:atk-bridge
QT_IM_MODULE=ibus
QT4_IM_MODULE=xim
GTK_IM_MODULE=ibus

**Comment by sk1project** [comment]
fixed
